branches:
  only:
    - master

install:
  - ps: wget https://storage.googleapis.com/dart-archive/channels/beta/release/latest/sdk/dartsdk-windows-x64-release.zip -OutFile dart-sdk.zip
  - cmd: echo "Unzipping dart-sdk..."
  - cmd: 7z x dart-sdk.zip -o"C:\tools" -y > nul
  - set PATH=%PATH%;C:\tools\dart-sdk\bin
  - set PATH=%PATH%;%APPDATA%\Pub\Cache\bin

build: off

test_script:
  - cd %TEST_DIR%
  - pub get
  - pub run test -j1

cache:
  - C:\Users\appveyor\AppData\Roaming\Pub\Cache